// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcofhchnyusryfzufclw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjb2ZoY2hueXVzcnlmenVmY2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODUwNjMsImV4cCI6MjA2NDk2MTA2M30.KJxItmjgwhPEFiJB0CxTrAm-0kGR-w9707wSWI4q54w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);